config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to:"tasks#index"
  
  # config/routes.rb
  resources :tasks

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord

  validates :task_name, presence: { message: I18n.t('validation.error_msg') }
  validates :description, presence: { message: I18n.t('validation.error_msg') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :set_locale

  def set_locale
    if I18n.available_locales.include?(params[:locale]&.to_sym)
      I18n.locale = params[:locale]
      session[:current_locale] = params[:locale]
    elsif session[:current_locale]
      I18n.locale = session[:current_locale] 
    end
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def index 
    end
end 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index 
    @task = Task.all.order( created_at: :desc )
  end

  def new
    @task = Task.new
  end

  def show 
    @task = Task.find(params["id"])
  end


  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:notice] = t('flash_msg.new')
      redirect_to action: :index 
    else
      render 'new'
    end
  end

  def update 

    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:notice] = t('flash_msg.update')
      redirect_to action: 'index' 
    else
      render :show
    end
  end

  def destroy
    @task = Task.find(params["id"])
    @task.destroy
    flash[:notice] = t('flash_msg.delete')
    redirect_to action: 'index'
  end
  

  private
  
  def task_params
    params.require(:task).permit(:task_name, :description, :done_at)
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<h1 class="text-3xl"> lorem  ipuse </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeginner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <div class="p-2">
      <%= yield %>  
      </div>
    </main>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container mx-auto px-4 py-8">
  <h2 class="text-3xl font-bold mb-6 text-center text-gray-800"><%= t('title')  %></h2>
  <div><%= Time.now %></div>
  <!--flash-->
  <% if flash[:notice] %>
    <div class="bg-green-200 p-4 rounded-sm mb-4"><%= flash.notice %></div>
  <% end %>
  <%= link_to t('add_task') , new_task_path , class: 'inline-block bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded mb-4' %>
  <div class="overflow-x-auto bg-white rounded-md shadow overflow-y-auto">
    <table class="border-collapse table-auto w-full whitespace-no-wrap bg-white table-striped relative">
      <thead>
        <tr class="text-left">
          <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-3 text-gray-600 font-bold tracking-wider text-xs"><%= t('table.title') %></th>
          <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-3 text-gray-600 font-bold tracking-wider text-xs"><%= t('table.description') %></th>
          <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-3 text-gray-600 font-bold tracking-wider text-xs"><%= t('table.created_at') %></th>
          <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-3 text-gray-600 font-bold tracking-wider text-xs"><%= t('table.done_at') %></th>
          <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-3 text-gray-600 font-bold tracking-wider text-xs"><%= t('table.actions') %></th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        <% @task.each do |table_item| %>
          <tr id=<%=table_item.id%>>
            <td class="border-t border-gray-200 px-6 py-4"><%= table_item.task_name %></td>
            <td class="border-t border-gray-200 px-6 py-4"><%= table_item.description %></td>
            <td class="border-t border-gray-200 px-6 py-4"><%= table_item.created_at %></td>
            <td class="border-t border-gray-200 px-6 py-4"><%= table_item.done_at == nil ? '未指定日期' : table_item.done_at %></td>
            <td class="border-t border-gray-200 px-6 py-4">
              <%= link_to t('table.action_edit'), task_path(table_item) , class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded "%>
              <%= link_to t('table.action_delete'), task_path(table_item) ,
              data: {turbo_method: :delete, turbo_confirm: t('table.delete_modal')} , class: "bg-red-500 hover:bg-red-500 text-white py-2 px-4 rounded " %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<h2><%= t('new.title') %></h2>


 
<%= form_with(model: @task, local: true ,data:{ turbo: false } ,class: "max-w-md mx-auto mt-8") do |form| %>
   
  <% if @task.errors.any? %>
    <div id="error_explanation" class="bg-red-200 p-2 ">
      <h2><%= pluralize(@task.errors.count, "error") %></h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :task_name, t('new.form_title') , class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :task_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, t('new.form_description') , class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-32" %>
  </div>

    <div class="mb-4">
    <%= form.label  t('new.done_at') , class: "block text-gray-700 text-sm font-bold mb-2" %>
    <div class='flex'>
      <%= form.datetime_field :done_at , class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
  
  <div class="flex items-center justify-between">
    <%= form.submit t('new.form_submit') , class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded" %>
  </div>
    
<% end %>

app/views/tasks/show.html.erb
<h2><%= t('update.title')%></h2>

<div class="container mx-auto max-w-80">
<%= form_with(model: @task, data: { turbo: false }, class: "py-10", id: 'task-form') do |form|  %>
  <% if @task.errors.any? %>
    <div id="error_explanation" class="bg-red-200 p-2 ">
      <h2><%= pluralize(@task.errors.count, "error") %></h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :task_name, t('update.form_title'), class:'block text-sm font-bold mb-2'%>
    <%= form.text_field :task_name ,  class:'shadow border rounded w-full py-2 px-3 focus:outline-none'%>
  </div>

  <div class='mt-4'>
    <%= form.label :description, t('update.form_description') , class: 'block text-sm font-bold mb-2' %>
    <%= form.text_area :description , class: 'shadow border rounded w-full py-2 px-3 focus:outline-none ' %>
  </div>

  <div class="mb-4">
    <%= form.label :done_at, t('new.done_at') , class: "block text-gray-700 text-sm font-bold mb-2" %>
    <div class='flex'>
    <%# <%= form.date_field :date , value: @task.done_at&.strftime("%Y-%M-%d") ,  class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= form.datetime_field :done_at  ,  class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
  </div>

  <div>
    <%= form.submit t('update.form_submit') , class:'bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded' %>
  </div>
<% end %>

<%= link_to t('update.go_back'), tasks_path %>    
</div>